"Project-specific vimrc set-up (c)

"set spacing
set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab

"limit line length
set colorcolumn=110
highlight ColorColumn ctermbg=darkgray


augroup project
    autocmd!
    autocmd BufRead,BufNewFile *.h,*.c set filetype=c.doxygen
augroup END

let &path.="src/include,/usr/include/AL,"

set includeexpr=substitute(v:fname,'\\.','/','g')

let g:ycm_extra_conf_globlist = 'ADD-PATH-HERE'

